services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
       db:
         condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://localhost:5432/RomanianAirports
  db:
   image: postgres
   restart: always
   volumes:
     - db-data:/var/lib/postgresql/data
   environment:
     - POSTGRES_DB=db_name
     - POSTGRES_USER=username
     - POSTGRES_PASSWORD=password
   expose:
     - 5432:5432
   healthcheck:
     test: [ "CMD", "pg_isready","-U", "username" ]
     interval: 10s
     timeout: 5s
     retries: 5
volumes:
 db-data:
